import { Inter } from "next/font/google";
import type { Metadata } from "next";

import { RepositoryContextProvider } from "@/context/RepositoryContext";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased">
        <RepositoryContextProvider>
          <div className="p-4 max-w-6xl mx-auto w-full h-full min-h-screen">
            {children}
          </div>
        </RepositoryContextProvider>
      </body>
    </html>
  );
}
