import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-react-dark">
        <div className="p-4 max-w-6xl mx-auto w-full h-full min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
